# Generated by Django 3.2.4 on 2021-06-09 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_fname', models.CharField(default='None', max_length=200)),
                ('patient_lname', models.CharField(default='None', max_length=200)),
                ('patient_dob', models.DateTimeField(default='None')),
                ('patient_allergies', models.CharField(default='None', max_length=1)),
                ('patient_state', models.CharField(default='None', max_length=200)),
                ('patient_zip', models.CharField(default='None', max_length=200)),
                ('patient_city', models.CharField(default='None', max_length=200)),
                ('patient_street', models.CharField(default='None', max_length=200)),
                ('patient_phone', models.CharField(default='None', max_length=200)),
                ('patient_partially_vacc', models.CharField(default='None', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supp_name', models.CharField(default='None', max_length=200)),
                ('supp_num_doses', models.CharField(default='None', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccinator_fname', models.CharField(default='None', max_length=200)),
                ('vaccinator_lname', models.CharField(default='None', max_length=200)),
                ('vaccinator_occupation', models.CharField(default='None', max_length=200)),
                ('vaccinator_phone', models.CharField(default='None', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacc_brand', models.CharField(default='None', max_length=200)),
                ('supp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dist_name', models.CharField(default='None', max_length=200)),
                ('dist_phone', models.CharField(default='None', max_length=200)),
                ('dist_num_doses', models.CharField(default='None', max_length=200)),
                ('dist_state', models.CharField(default='None', max_length=200)),
                ('dist_zip', models.CharField(default='None', max_length=200)),
                ('dist_city', models.CharField(default='None', max_length=200)),
                ('dist_street', models.CharField(default='None', max_length=200)),
                ('supp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_start', models.DateTimeField(default='None')),
                ('app_end', models.DateTimeField(default='None')),
                ('app_state', models.CharField(default='None', max_length=200)),
                ('app_zip', models.CharField(default='None', max_length=200)),
                ('app_city', models.CharField(default='None', max_length=200)),
                ('app_street', models.CharField(default='None', max_length=200)),
                ('distributor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.distributor')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.patient')),
                ('vaccinator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.vaccinator')),
                ('vaccine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.vaccine')),
            ],
        ),
    ]
