# Generated by Django 3.2.4 on 2021-06-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='app_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='app_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_dob',
            field=models.DateTimeField(null=True),
        ),
    ]
