# Generated by Django 3.2.4 on 2021-06-13 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20210609_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_allergies',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_dob',
            field=models.DateTimeField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_partially_vacc',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
