# Generated by Django 3.1.1 on 2021-06-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20210613_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='app_city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='app_state',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='app_street',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='app_zip',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='dist_city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='dist_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='dist_num_doses',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='dist_phone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='dist_state',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='dist_street',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='dist_zip',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_fname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_lname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_phone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_state',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_street',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_zip',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supp_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supp_num_doses',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vaccinator',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vaccinator',
            name='vaccinator_fname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vaccinator',
            name='vaccinator_lname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vaccinator',
            name='vaccinator_occupation',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vaccinator',
            name='vaccinator_phone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='vacc_brand',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
